# Use current version of Node.js
image: node:current-alpine

# Install dependencies
before_script:
  - npm install

# Cache dependencies in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

# Run tests
test:
  stage: test
  script:
    - npm run test

# Publish to package registry (this job may fail in case of same package version as one already in registry)
publish:
  stage: deploy
  allow_failure: true
  script:
    - cat $CI_NPMRC > .npmrc
    - npm publish
  only:
    - release
